

export const employees=[
    {name:"geeta",
    designation:"reactdeveloper",
salary:10000},
{name:"rani",
designation:"angulardeveloper",
salary:25000},
{name:"kiran",
designation:"nodejsdeveloper",
salary:35000},
{name:"sita",
designation:"pythondeveloper",
salary:20000},
{name:"ram",
designation:"angulartdeveloper",
salary:19000},
{name:"karan",
designation:"pythontdeveloper",
salary:10000},
{name:"lavanya",
designation:"nodejsdeveloper",
salary:20000},
{name:"gayatri",
designation:"reactdeveloper",
salary:29000},
{name:"mani",
designation:"pythondeveloper",
salary:12000},
{name:"priya",
designation:"reactdeveloper",
salary:45000},

]